min_version = "2026.8.14"

[settings]
lockfile = true

[tool_config]
locked = true

[tools]
go = "1.27.1"
"aqua:goreleaser/goreleaser" = "2.18.0"
"go:github.com/google/go-licenses/v2" = "v2.0.1"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.7.0"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.7.1",
]
